name: non_promotion_examples
description: dart.dev non-promotion examples.
version: 0.0.1

resolution: workspace
environment:
  sdk: ^3.5.3

dependencies:
  mockito: ^5.4.4

dev_dependencies:
  lints: ^4.0.0
