# Site settings
title: Dart
description: >-
  Dart is a client-optimized language for developing fast apps on any platform.
url: https://dart.dev
repo:
  this: https://github.com/dart-lang/site-www
  shared: https://github.com/dart-lang/site-shared
branch: main
port: 4000
source: src

strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
future: true # In support of https://github.com/dart-lang/site-www/issues/1111
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - ../node_modules/bootstrap-scss
plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 3
  no_toc_section_class: no_toc_section


flutter: https://flutter.dev
flutter-docs: https://docs.flutter.dev
dart-api: https://api.dart.dev
flutter-api: https://api.flutter.dev
pub: https://pub.dev
pub-api: https://pub.dev/documentation
pub-pkg: https://pub.dev/packages
dartpad: https://dartpad.dev
news: https://news.dartlang.org
announce: https://groups.google.com/a/dartlang.org/g/announce

show_banner: true

defaults:
- scope:
    path: ''
    # type: pages
  values:
    layout: default
    toc: true

# Increment this global og:image URL version number (used as a query parameter)
# when you update any og:image file. (Also increment the corresponding number
# in the `firebase.json` redirect rule.)
og_image_vers: "?2"


## Site-wide shorthands

alert:
  important: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">error</i> **Important:**
  info: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">info</i>
  note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">info</i> **Note:**
  flutter-note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <img src="/assets/img/shared/flutter/icon/64.png" width="24" alt="Flutter logo"> **Flutter note:**
  version-note: >-
    <aside class="alert alert-info" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">merge_type</i> **Version note:**
  secondary: >-
    <aside class="alert alert-secondary" role="alert" markdown="1">
  tip: >-
    <aside class="alert alert-success" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">tips_and_updates</i> **Tip:**
  warn: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">report_problem</i>
  warning: >-
    <aside class="alert alert-warning" role="alert" markdown="1">
    <i class="material-icons" aria-hidden="true">report_problem</i> **Warning:**
  end: </aside>

why:
  learn: >-
    <div class="mini-toc" markdown="1">
      <h4 class="no_toc">What you'll learn</h4>
  end: </div>
