name: site_www

homepage: https://dart.dev

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.0
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  linkcheck: ^2.0.19
  lints: ^2.0.0
