name: dart_dev
publish_to: none
homepage: https://dart.dev

environment:
  sdk: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.6
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  dart_site:
    path: tool/dart_site
  lints: ^3.0.0
