name: site_www
publish_to: none

homepage: https://dart.dev

environment:
  sdk: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.4
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  linkcheck: ^3.0.0
  lints: ^2.1.0
  logging: ^1.2.0
  path: ^1.8.3
