name: download_archive
description: Display a list of downloads for dart.dev.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.8.0-0

dependencies:
  dart_sdk_archive:
    path: ../dart_sdk_archive

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
