name: dart_dev_site
publish_to: none
homepage: https://dart.dev

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  build: ^4.0.3
  collection: ^1.19.1
  crypto: ^3.0.7
  # Used for accessing the SDK archive storage buckets.
  googleapis: ^15.0.0
  html: ^0.15.6
  http: ^1.6.0
  # Used for formatting dates in the SDK archive.
  intl: ^0.20.2
  jaspr: ^0.22.2
  jaspr_content: ^0.4.5
  # Used as our template engine.
  liquify: 1.3.1
  markdown: ^7.3.0
  markdown_description_list: ^0.1.1
  meta: ^1.17.0
  # Used for syntax highlighting.
  nanoid2: ^2.0.1
  opal: ^0.2.1
  path: ^1.9.1
  # Used in the SDK archive.
  pub_semver: ^2.2.0
  universal_web: ^1.1.1+1
  yaml: ^3.1.3

dev_dependencies:
  analysis_defaults:
    git:
      url: https://github.com/dart-lang/site-shared
      path: pkgs/analysis_defaults
      ref: e2534e272132813a1cdcf6ea71a6fd9c904a69fb
  build_runner: ^2.10.4
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.2
  jaspr_test: ^0.22.2
  lints: ^6.0.0
  sass: ^1.94.2
  sass_builder: ^2.4.0

jaspr:
  mode: static
