name: dart_dev_site
publish_to: none
homepage: https://dart.dev

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  # Used for accessing the SDK archive storage buckets.
  googleapis: ^14.0.0
  html: ^0.15.6
  http: ^1.4.0
  # Used for formatting dates in the SDK archive.
  intl: ^0.20.2
  jaspr: ^0.21.0-dev.1
  jaspr_content: ^0.3.1-dev.1
  # Used as our template engine.
  liquify: ^1.3.0
  markdown: ^7.3.0
  meta: ^1.17.0
  # Used for syntax highlighting.
  opal: ^0.0.1
  path: ^1.9.1
  # Used in the SDK archive.
  pub_semver: ^2.2.0
  web: ^1.1.1

dev_dependencies:
  analysis_defaults:
    path: ../site-shared/pkgs/analysis_defaults
  build_runner: ^2.7.1
  build_web_compilers: ^4.2.3
  jaspr_builder: ^0.21.0-dev.1
  sass: ^1.92.1
  sass_builder: ^2.3.1

dependency_overrides:
  # Remove once the next stable release of Jaspr has been published.
  jaspr:
    git:
      url: https://github.com/schultek/jaspr.git
      path: packages/jaspr
      ref: b7a8b00e2dd4c4d907fb6377739269d29bac6849
  jaspr_builder:
    git:
      url: https://github.com/schultek/jaspr.git
      path: packages/jaspr_builder
      ref: b7a8b00e2dd4c4d907fb6377739269d29bac6849
  jaspr_content:
    git:
      url: https://github.com/schultek/jaspr.git
      path: packages/jaspr_content
      ref: b7a8b00e2dd4c4d907fb6377739269d29bac6849
  jaspr_router:
    git:
      url: https://github.com/schultek/jaspr.git
      path: packages/jaspr_router
      ref: b7a8b00e2dd4c4d907fb6377739269d29bac6849

jaspr:
  mode: static
