name: build_runner_usage
description: dart.dev build_runner example code.

resolution: workspace
environment:
  sdk: ^3.10.0

dev_dependencies:
  args: ^2.7.0
  build_runner: ^2.10.4
  build_test: ^3.5.4
