name: build_runner_usage
description: dart.dev build_runner example code.

resolution: workspace
environment:
  sdk: ^3.9.0-0

dev_dependencies:
  args: ^2.7.0
  build_runner: ^2.4.15
  build_test: any
