name: build_runner_usage
description: dart.dev build_runner example code.

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  lints: ^1.0.0
