name: dash_site
description: Dart-based tools for building dart.dev.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  excerpter:
    git:
      url: https://github.com/dart-lang/site-shared
      path: pkgs/excerpter
      ref: e2534e272132813a1cdcf6ea71a6fd9c904a69fb
  fbh_front_matter: ^0.0.1
  html_unescape: ^2.0.0
  http: ^1.6.0
  intl: ^0.20.2
  io: ^1.0.5
  linkcheck: ^3.1.0
  markdown: ^7.3.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3
  yaml_variable_scanner: ^0.0.7

dev_dependencies:
  analysis_defaults:
    git:
      url: https://github.com/dart-lang/site-shared
      path: pkgs/analysis_defaults
      ref: e2534e272132813a1cdcf6ea71a6fd9c904a69fb
