name: examples_workspace
publish_to: none

resolution: workspace
environment:
  sdk: ^3.11.0

workspace:
  - analysis
  - analysis_alt
  - async_await
  - build_runner_usage
  - cli
  - concurrency
  - create_libraries
  - extension_methods
  - fetch_data
  - futures
  - html
  - iterables
  - language
  - misc
  - non_promotion
  - type_system
  - util
  - vector_victor

dev_dependencies:
  lints: ^6.0.0
