name: null_safety_codelab_examples
description: dart.dev example code for null safety codelab

environment:
  sdk: ^3.1.0

dev_dependencies:
  examples_util: {path: ../util}
  lints: ^2.1.0
  test: ^1.24.6
