name: null_safety_codelab_examples
description: dart.dev example code for null safety codelab

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  examples_util: {path: ../util}
  lints: ^2.0.0
  test: ^1.19.2
