name: vector_victor
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

resolution: workspace
environment:
  sdk: ^3.10.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.28.0

dependencies:
  vector_math: ^2.2.0
