name: vector_victor
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.4.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2

dependencies:
  vector_math: ^2.1.4
