name: sdk_builds
description: Utilities for accessing builds of the Dart SDK.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.7.0

dependencies:
  googleapis: ^14.0.0
  http: ^1.3.0
  path: ^1.9.0
  pub_semver: ^2.2.0

dev_dependencies:
  test: ^1.25.8
