name: examples
description: dart.dev example code.

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  characters: ^1.3.0
  examples_util: { path: ../util }

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.6
