name: examples
description: dart.dev example code.

resolution: workspace
environment:
  sdk: ^3.10.0-0

dependencies:
  args: ^2.7.0
  characters: ^1.3.0
  examples_util: { path: ../util }
  http: ^1.4.0
  meta: ^1.17.0
  web: ^1.1.0

dev_dependencies:
  test: ^1.26.0
