name: examples
description: dart.dev example code.

resolution: workspace
environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  characters: ^1.4.1
  examples_util: { path: ../util }
  http: ^1.6.0
  meta: ^1.17.0
  web: ^1.1.1

dev_dependencies:
  test: ^1.28.0
