name: futures_examples
description: dart.dev futures and error handling examples.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  examples_util: {path: ../util}

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.6
