name: futures_examples
description: dart.dev futures and error handling examples.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  examples_util: {path: ../util}

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.2
