name: type_system_examples
description: dart.dev type system examples.

resolution: workspace
environment:
  sdk: ^3.5.3

dependencies:
  examples_util: {path: ../util}

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
