name: type_system_examples
description: dart.dev type system examples.

resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  examples_util: {path: ../util}
  web: ^1.1.1

dev_dependencies:
  test: ^1.28.0
