name: type_system_examples
description: dart.dev type system examples.

resolution: workspace
environment:
  sdk: ^3.6.1

dependencies:
  examples_util: {path: ../util}

dev_dependencies:
  test: ^1.25.8
