name: fetch_data_examples
description: Fetch data example
version: 0.0.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.0.0
  lints: ^2.0.0
  test: ^1.19.2
