name: concurrency_examples
description: dart.dev concurrency examples.
version: 0.0.1
publish_to: none

resolution: workspace
environment:
  sdk: ^3.7.0

dependencies:
  http: any

dev_dependencies:
  test: ^1.25.8
