name: html_library_examples
description: dart.dev example code.
version: 0.0.1

environment:
  sdk: ^2.19.4

dependencies:
  html: any

dev_dependencies:
  test: ^1.19.2
  lints: ^2.0.0
  examples_util: {path: ../util}
