name: deprecated_html_library_examples
description: Deprecated dart.dev example code.
version: 0.0.1

resolution: workspace
environment:
  sdk: ^3.10.0

dev_dependencies:
  test: ^1.26.0
  examples_util: {path: ../util}
