name: dart_sdk_archive
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.1
  intl: ^0.17.0
  path: ^1.8.0
  pub_semver: ^2.1.1
  sdk_builds:
    path: ../sdk_builds.dart

dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.0.0
  dart_style: ^2.2.0
  grinder: ^0.9.0
  lints: ^2.0.0
  test: ^1.19.2
