name: dart_sdk_archive
description: An absolute bare-bones web app.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.2.2
  intl: ^0.20.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  sdk_builds:
    path: ../sdk_builds
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  dart_style: ^2.3.7
  grinder: ^0.9.5
  test: ^1.25.8
