name: dart_sdk_archive
description: An absolute bare-bones web app.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.0
  intl: ^0.19.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  sdk_builds:
    path: ../sdk_builds.dart
  web: ^0.5.1

dev_dependencies:
  analysis_defaults:
    path: ../../../site-shared/packages/analysis_defaults
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  dart_style: ^2.3.6
  grinder: ^0.9.5
  test: ^1.25.2
