name: dart_sdk_archive
description: An absolute bare-bones web app.
publish_to: none

resolution: workspace
environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.4.0
  intl: ^0.20.2
  jaspr: ^0.18.0
  path: ^1.9.0
  pub_semver: ^2.2.0
  sdk_builds:
    path: ../sdk_builds
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
  dart_style: ^3.0.1
  grinder: ^0.9.5
  jaspr_test: ^0.18.0
  test: ^1.26.0
