name: effective_dart_rules
description: Builds a file with all the rules in the different sections of Effective Dart.
version: 0.0.3

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  html_unescape: ^2.0.0
  markdown: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
