name: test

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  # Configure analytics reporting for pub.
  PUB_ENVIRONMENT: bot.github
  # The Node version to use for site infra. Generally should be the latest LTS.
  NODE_VERSION: '22'

jobs:
  test:
    name: Analyze and test code examples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk: beta
            experimental: false
          - sdk: stable
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}
      - name: Fetch Dart packages
        run: dart pub get
        continue-on-error: ${{ matrix.experimental }}
      - name: Check Dart code formatting
        run: dart run dart_site format-dart --check
        continue-on-error: ${{ matrix.experimental }}
      - name: Analyze Dart code
        run: dart run dart_site analyze-dart
        continue-on-error: ${{ matrix.experimental }}
      - name: Run Dart tests
        run: dart run dart_site test-dart
        continue-on-error: ${{ matrix.experimental }}

  markdown-check:
    name: Check Markdown content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - name: Fetch Dart packages
        run: dart pub get
      - name: Check Markdown for any known issues
        run: dart run dart_site check-markdown

  excerpts:
    name: Check if code excerpts are up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - name: Fetch Dart packages
        run: dart pub get
      - name: Check if excerpts are up to date
        run: dart run dart_site refresh-excerpts --fail-on-update --dry-run

  site-variable-scanner:
    name: Check if text can be replaced with site variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - name: Fetch Dart packages
        run: dart pub get
      - name: Check if text can be replaced with site variables
        run: dart run dart_site check-site-variable

  firebase-validate:
    name: Validate Firebase configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: beta
      - name: Fetch Dart packages
        run: dart pub get
      - name: Validate the firebase.json file
        run: dart run dart_site verify-firebase-json
