name: language_examples
description: dart.dev example code.

resolution: workspace
environment:
  sdk: ^3.11.0

dependencies:
  charcode: ^1.4.0
  examples_util: { path: ../util }
  meta: ^1.17.0

dev_dependencies:
  test: ^1.28.0
